version: '3.8'

services:
  rust-training-book:
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      CARGO_BUILD_TARGET_DIR: /app/target
