Vagrant.configure('2') do |config|
  config.vm.define :node1 do |node|
    node.vm.box = 'centos64_6_5'
    node.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box'
    node.vm.network :forwarded_port, guest: 22, host: 2001, id: 'ssh'
    node.vm.network :private_network, ip: '192.168.33.11'
    node.vm.provision 'shell', privileged: false, inline: 'sudo yum install -y epel-release'
    node.vm.provision 'shell', privileged: false, inline: 'sudo yum install -y ansible'
    node.vm.provision 'shell', inline: "echo '192.168.33.12' >>  /etc/ansible/hosts"
    node.vm.provision 'shell', inline: "echo '[all:vars]' >>  /etc/ansible/hosts"
    node.vm.provision 'shell', inline: "echo 'ansible_ssh_user=vagrant' >>  /etc/ansible/hosts"
    node.vm.provision 'shell', inline: "echo 'ansible_ssh_pass=vagrant' >>  /etc/ansible/hosts"
  end

  config.vm.define :node2 do |node|
    node.vm.box = 'centos64_6_5'
    node.vm.network :forwarded_port, guest: 22, host: 2002, id: 'ssh'
    node.vm.network :forwarded_port, guest: 80, host: 8000, id: 'http'
    node.vm.network :private_network, ip: '192.168.33.12'
  end
end
