version: "3"
services:
  jupyter_mysql:
    image: mysql:8.0.28-oracle
    volumes:
      - "jupyter-mysql-data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: jupyter_db
    ports:
     - 13306:3306
    environment:
      MYSQL_DATABASE: jupyter
      MYSQL_USER: jupyter_user
      MYSQL_PASSWORD: jupyter_pass
      MYSQL_ROOT_PASSWORD: password

  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - "../:/home/jovyan/work"
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  jupyter-mysql-data:
