Vagrant.configure('2') do |config|
  config.vm.define :node1 do |node|
    node.vm.box = 'centos64_6_8'
    node.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.8_chef-provisionerless.box'
    node.vm.network :forwarded_port, guest: 22, host: 2001, id: 'ssh'
    node.vm.network :private_network, ip: '192.168.33.11'
    node.vm.provision 'shell', privileged: false, inline: 'sudo yum install -y epel-release'
    node.vm.provision 'shell', privileged: false, inline: 'sudo yum install -y ansible'
    node.vm.synced_folder "./ansible_files", "/home/vagrant/ansible_files", owner: "vagrant", group: "vagrant"
  end

  config.vm.define :node2 do |node|
    node.vm.box = 'centos64_6_8'
    node.vm.network :forwarded_port, guest: 22, host: 2002, id: 'ssh'
    node.vm.network :forwarded_port, guest: 80, host: 8001, id: 'http'
    node.vm.network :private_network, ip: '192.168.33.12'
  end

  config.vm.define :node3 do |node|
    node.vm.box = 'centos64_6_8'
    node.vm.network :forwarded_port, guest: 22, host: 2003, id: 'ssh'
    node.vm.network :forwarded_port, guest: 80, host: 8002, id: 'http'
    node.vm.network :private_network, ip: '192.168.33.13'
  end
end
